-- ════════════════════════════════════════════════════════════════════════════
-- FRESHGO TEST BASELINE — PRE-RELEASE SCHEMA (bootstrap only)
--
-- The repository's migration history (supabase/migrations/) assumes two
-- tables already exist because they were created before the migration era:
--   * "Orders"        — the app's core table; migration 20260712051341 only
--                       ALTERs it and its header explicitly says RLS was
--                       "already enabled".
--   * site_settings   — never created in migrations; only INSERTed/read.
-- Without this baseline, replaying the migrations on a clean database fails at
-- the very first migration.
--
-- This file is NOT an application migration. It lives OUTSIDE supabase/migrations/
-- and exists only to let a fresh TEST project be bootstrapped.
--
-- Apply BEFORE supabase/migrations/*.sql on a fresh database.
-- Never run against production.
-- ════════════════════════════════════════════════════════════════════════════

-- ── Core order table ────────────────────────────────────────────────────────
CREATE TABLE "Orders" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);
ALTER TABLE "Orders" ENABLE ROW LEVEL SECURITY;

-- ── Site/key-value settings table ───────────────────────────────────────────
CREATE TABLE public.site_settings (
  key        text PRIMARY KEY,
  value      jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);