/* eslint-disable @typescript-eslint/no-explicit-any -- legacy preparation API returns ungenerated row shapes. */
import { useEffect, useState } from 'react';
import { Navigate, Link } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Loader2, Plus, Save } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { fetchProducts } from '../data/products';
import {
  assignPublishedSchema, createDraftVersion, createPreparationSchema, listPreparationSchemas,
  loadVersionQuestions, publishPreparationVersion, replaceDraftQuestions,
  type PreparationSchema, type PreparationVersion, type PrepQuestionDraft,
} from '../data/preparationConfigurations';

const input = 'w-full rounded-xl border border-cream-200 bg-cream-50 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-forest-500';
const chickenQuestions: PrepQuestionDraft[] = [
  { code: 'cut_size', label: 'Cut size', label_ms: 'Saiz potongan', help_text: 'Choose how the chicken should be cut.', help_text_ms: 'Pilih cara ayam dipotong.', answer_type: 'single_select', selection_scope: 'physical_unit', required: true, options: ['2', '4', '9', '12', '14', '16', '24'].map((code) => ({ code, label: `${code} pieces`, label_ms: `${code} bahagian` })) },
  ...[['organs', 'Keep organs?', 'Simpan organ?'], ['head', 'Keep head?', 'Simpan kepala?'], ['feet', 'Keep feet?', 'Simpan kaki?']].map(([code, label, label_ms]) => ({ code, label, label_ms, help_text: '', help_text_ms: '', answer_type: 'boolean' as const, selection_scope: 'physical_unit' as const, required: true, options: [{ code: 'yes', label: 'Yes', label_ms: 'Ya' }, { code: 'no', label: 'No', label_ms: 'Tidak' }] })),
];
const fishQuestions: PrepQuestionDraft[] = [
  { code: 'clean_gut', label: 'Clean and gut?', label_ms: 'Bersihkan dan buang perut?', help_text: '', help_text_ms: '', answer_type: 'boolean', selection_scope: 'physical_unit', required: true, options: [{ code: 'yes', label: 'Yes', label_ms: 'Ya' }, { code: 'no', label: 'No', label_ms: 'Tidak' }] },
  { code: 'cut_method', label: 'Cut method', label_ms: 'Kaedah potongan', help_text: 'Options can be adjusted for this product or schema.', help_text_ms: 'Pilihan boleh diubah untuk produk atau skema ini.', answer_type: 'single_select', selection_scope: 'physical_unit', required: true, options: [['whole', 'Whole', 'Seekor'], ['two_parts', 'Two parts', 'Dua bahagian'], ['slice', 'Slice', 'Hirisan'], ['butterfly', 'Butterfly', 'Rama-rama']].map(([code, label, label_ms]) => ({ code, label, label_ms })) },
];
const blankQuestion = (): PrepQuestionDraft => ({ code: '', label: '', label_ms: '', help_text: '', help_text_ms: '', answer_type: 'single_select', selection_scope: 'physical_unit', required: false, options: [] });

export default function AdminPreparationConfigurationsPage() {
  const { isAdmin, loading: authLoading } = useAuth(); const { t } = useLanguage();
  const [schemas, setSchemas] = useState<PreparationSchema[]>([]); const [products, setProducts] = useState<{ id: string; name: string; category: string }[]>([]);
  const [schema, setSchema] = useState<PreparationSchema | null>(null); const [version, setVersion] = useState<PreparationVersion | null>(null);
  const [questions, setQuestions] = useState<PrepQuestionDraft[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [newSchema, setNewSchema] = useState({ code: '', name: '', name_ms: '', description: '', description_ms: '' }); const [productId, setProductId] = useState('');
  const refresh = async () => { const [nextSchemas, nextProducts] = await Promise.all([listPreparationSchemas(), fetchProducts(true)]); setSchemas(nextSchemas); setProducts(nextProducts.map((p) => ({ id: p.id, name: p.name, category: p.category }))); return nextSchemas; };
  useEffect(() => { if (isAdmin) refresh().catch((e) => setError(e.message)); }, [isAdmin]);
  const selectVersion = async (nextSchema: PreparationSchema, nextVersion: PreparationVersion) => { setSchema(nextSchema); setVersion(nextVersion); setQuestions((await loadVersionQuestions(nextVersion.id)).map((q: any) => ({ ...q, options: q.preparation_question_options ?? [] }))); setMessage(''); };
  if (authLoading) return <div className="min-h-[50vh] flex items-center justify-center"><Loader2 className="animate-spin text-forest-600" /></div>;
  if (!isAdmin) return <Navigate to="/" replace />;
  const updateQuestion = (index: number, patch: Partial<PrepQuestionDraft>) => setQuestions((all) => all.map((q, i) => i === index ? { ...q, ...patch } : q));
  const create = async (preset?: PrepQuestionDraft[]) => { setBusy(true); setError(''); try { const made = await createPreparationSchema(newSchema); const next = await refresh(); const selected = next.find((s) => s.id === made.schema.id)!; await selectVersion(selected, made.version); setQuestions(preset ?? []); setMessage('Draft created. Add or edit questions, then save.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const saveQuestions = async () => { if (!version) return; setBusy(true); setError(''); try { await replaceDraftQuestions(version.id, questions); setMessage('Draft questionnaire saved.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const publish = async () => { if (!version) return; setBusy(true); setError(''); try { await saveQuestions(); await publishPreparationVersion(version.id); const next = await refresh(); const selected = next.find((s) => s.id === schema!.id)!; await selectVersion(selected, selected.preparation_schema_versions.find((v) => v.id === version.id)!); setMessage('Version published and now visible to storefront reads.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const newVersion = async () => { if (!schema) return; setBusy(true); try { const v = await createDraftVersion(schema); const next = await refresh(); await selectVersion(next.find((s) => s.id === schema.id)!, v); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const assign = async () => { if (!productId || !version || version.status !== 'published') return setError('Select a product and a published schema version.'); setBusy(true); setError(''); try { const product = products.find((p) => p.id === productId); await assignPublishedSchema(productId, version.id, product?.category === 'chicken' ? 'chicken' : product?.category === 'fish' ? 'fish' : 'other'); setMessage('Published schema version assigned to this product. Checkout remains unchanged until Phase 3.'); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  return <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8"><Link to="/admin/products" className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-forest-700"><ArrowLeft size={16} /> {t('preparationConfig.back')}</Link><h1 className="mt-4 text-3xl font-display font-bold text-charcoal">{t('preparationConfig.title')}</h1><p className="mt-2 text-gray-600">{t('preparationConfig.subtitle')}</p>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-700"><CheckCircle2 className="inline mr-2" size={16} />{message}</p>}
    <section className="mt-6 rounded-2xl border border-cream-200 bg-white p-5"><h2 className="font-bold">{t('preparationConfig.newSchema')}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{(['code','name','name_ms','description','description_ms'] as const).map((key) => <input key={key} className={input} placeholder={t(`preparationConfig.${key}`)} value={newSchema[key]} onChange={(e) => setNewSchema({ ...newSchema, [key]: e.target.value })} />)}</div><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy || !newSchema.code || !newSchema.name} onClick={() => create()} className="btn-secondary">{t('preparationConfig.blank')}</button><button disabled={busy || !newSchema.code || !newSchema.name} onClick={() => create(chickenQuestions)} className="btn-primary">{t('preparationConfig.chickenPreset')}</button><button disabled={busy || !newSchema.code || !newSchema.name} onClick={() => create(fishQuestions)} className="btn-primary">{t('preparationConfig.fishPreset')}</button></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border border-cream-200 bg-white p-4"><h2 className="font-bold">{t('preparationConfig.schemas')}</h2>{schemas.map((s) => <div key={s.id} className="mt-3"><button onClick={() => { setSchema(s); setVersion(null); }} className="font-medium text-forest-700">{s.name} <span className="text-xs text-gray-500">({s.code})</span></button>{s.preparation_schema_versions?.map((v) => <button key={v.id} onClick={() => selectVersion(s, v)} className="ml-3 mt-1 block text-sm text-gray-600 hover:text-forest-700">v{v.version_number} · {v.status}</button>)}</div>)}</aside>
      <section className="rounded-2xl border border-cream-200 bg-white p-5">{!version ? <p className="text-gray-500">{t('preparationConfig.selectVersion')}</p> : <><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{schema?.name} · v{version.version_number}</h2><p className="text-sm text-gray-500">{version.status}</p></div>{version.status === 'draft' && <div className="flex gap-2"><button onClick={newVersion} className="btn-secondary">{t('preparationConfig.newDraft')}</button><button onClick={publish} disabled={busy} className="btn-primary">{t('preparationConfig.publish')}</button></div>}</div>
        {version.status === 'draft' && <><div className="mt-4 flex justify-between"><h3 className="font-semibold">{t('preparationConfig.questions')}</h3><button className="btn-secondary text-sm" onClick={() => setQuestions([...questions, blankQuestion()])}><Plus size={15} /> {t('preparationConfig.addQuestion')}</button></div>{questions.map((q, i) => <div key={i} className="mt-3 rounded-xl bg-cream-50 p-3"><div className="grid gap-2 md:grid-cols-3"><input className={input} placeholder="code" value={q.code} onChange={(e) => updateQuestion(i, { code: e.target.value })}/><input className={input} placeholder="English label" value={q.label} onChange={(e) => updateQuestion(i, { label: e.target.value })}/><input className={input} placeholder="Label Bahasa Melayu" value={q.label_ms} onChange={(e) => updateQuestion(i, { label_ms: e.target.value })}/><select className={input} value={q.answer_type} onChange={(e) => updateQuestion(i, { answer_type: e.target.value as PrepQuestionDraft['answer_type'] })}>{['boolean','single_select','multi_select','integer','decimal','text'].map((x) => <option key={x}>{x}</option>)}</select><select className={input} value={q.selection_scope} onChange={(e) => updateQuestion(i, { selection_scope: e.target.value as PrepQuestionDraft['selection_scope'] })}><option value="physical_unit">physical unit</option><option value="line">line</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={q.required} onChange={(e) => updateQuestion(i, { required: e.target.checked })}/>Required</label></div><input className={`${input} mt-2`} placeholder="Options: code|English|Malay, … (not needed for text/number)" value={q.options.map((o) => `${o.code}|${o.label}|${o.label_ms}`).join(', ')} onChange={(e) => updateQuestion(i, { options: e.target.value.split(',').map((x) => x.trim()).filter(Boolean).map((x) => { const [code, label = '', label_ms = ''] = x.split('|'); return { code, label, label_ms }; }) })}/></div>)}<button disabled={busy} onClick={saveQuestions} className="btn-primary mt-4"><Save size={16} /> {t('preparationConfig.saveDraft')}</button></>}
        <div className="mt-6 rounded-xl border border-dashed border-forest-300 p-4"><h3 className="font-semibold">{t('preparationConfig.preview')}</h3>{questions.map((q) => <div key={q.code} className="mt-3"><p className="font-medium">{q.label} <span className="text-gray-500">/ {q.label_ms}</span></p><p className="text-sm text-gray-500">{q.options.map((o) => o.label).join(' · ') || q.answer_type}</p></div>)}</div>
        {version.status === 'published' && <div className="mt-6 rounded-xl bg-forest-50 p-4"><h3 className="font-semibold">{t('preparationConfig.assign')}</h3><div className="mt-2 flex flex-wrap gap-2"><select className={input} value={productId} onChange={(e) => setProductId(e.target.value)}><option value="">{t('preparationConfig.selectProduct')}</option>{products.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button onClick={assign} disabled={busy} className="btn-primary">{t('preparationConfig.assign')}</button></div></div>}</>}</section></div></main>;
}
