import { BellOff, BellRing } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { backgroundPushDiagnostic, disableWebPush, enableWebPush, hasActiveWebPushSubscription, pushSupportState, webPushWorkerDiagnostic, type PushSupportState } from '../../pwa/webPush';

export default function PushNotificationControl() {
  const { language } = useLanguage();
  const [state, setState] = useState<PushSupportState>(() => pushSupportState());
  const [enabled, setEnabled] = useState(false); const [subscriptionChecked, setSubscriptionChecked] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [workerMessage, setWorkerMessage] = useState<string | null>(null); const [backgroundMessage, setBackgroundMessage] = useState<string | null>(null);
  const malay = language === 'ms';
  useEffect(() => { void hasActiveWebPushSubscription().then(setEnabled).catch(() => setEnabled(false)).finally(() => setSubscriptionChecked(true)); }, []);
  const checkWorker = () => void webPushWorkerDiagnostic().then((diagnostic) => setWorkerMessage(diagnostic.detail)).catch(() => setWorkerMessage(malay ? 'Tidak dapat menyemak perkhidmatan notifikasi.' : 'Could not check the notification service.'));
  const checkBackgroundPush = () => void backgroundPushDiagnostic().then((diagnostic) => setBackgroundMessage(diagnostic.detail)).catch(() => setBackgroundMessage(malay ? 'Tidak dapat membaca rekod push latar belakang.' : 'Could not read the background push record.'));
  const toggle = async () => {
    setBusy(true); setMessage(null);
    try {
      if (enabled) { await disableWebPush(); setEnabled(false); setMessage(malay ? 'Notifikasi peranti dimatikan.' : 'Device notifications are off.'); }
      else { await enableWebPush(); setEnabled(true); setState(pushSupportState()); setMessage(malay ? 'Notifikasi peranti dihidupkan.' : 'Device notifications are on.'); }
    } catch (error) { setState(pushSupportState()); setMessage(error instanceof Error ? error.message : (malay ? 'Tidak dapat mengemas kini notifikasi.' : 'Could not update notifications.')); } finally { setBusy(false); }
  };
  const unavailable = state === 'unsupported' ? (malay ? 'Pelayar ini tidak menyokong notifikasi peranti.' : 'This browser does not support device notifications.') : state === 'missing_configuration' ? (malay ? 'Tetapan notifikasi FreshGo belum tersedia pada versi ini.' : 'FreshGo notification setup is unavailable in this version.') : state === 'denied' ? (malay ? 'Kebenaran notifikasi disekat. Buka tetapan laman Chrome, pilih Notifications, kemudian tekan Allow.' : 'Notification permission is blocked. Open Chrome site settings, choose Notifications, then tap Allow.') : null;
  const canUseControls = state === 'ready';
  return <div className="w-full min-w-0 rounded-xl border border-cream-200 bg-cream-50 p-3 sm:p-4"><p className="text-sm font-semibold text-charcoal">{malay ? 'Notifikasi peranti' : 'Device notifications'}</p><p className="mt-1 break-words text-xs leading-5 text-gray-600">{malay ? 'Terima kemas kini pesanan penting pada peranti ini.' : 'Receive important order updates on this device.'}</p>{unavailable ? <p className="mt-2 break-words text-xs leading-5 text-gray-600" role="status">{unavailable}</p> : subscriptionChecked && enabled ? <p className="mt-2 text-xs font-semibold text-forest-700" role="status">{malay ? 'Notifikasi dihidupkan pada peranti ini.' : 'Notifications are enabled on this device.'}</p> : null}<div className="mt-3 flex min-w-0 flex-col items-stretch gap-2 sm:flex-row sm:flex-wrap sm:items-center">{canUseControls ? <button type="button" onClick={() => void toggle()} disabled={busy || !subscriptionChecked} className="inline-flex min-h-11 min-w-0 items-center justify-center gap-2 rounded-xl border border-forest-200 bg-white px-3 text-xs font-semibold text-forest-800 disabled:opacity-60">{enabled ? <BellOff className="shrink-0" size={15} aria-hidden="true" /> : <BellRing className="shrink-0" size={15} aria-hidden="true" />}<span className="break-words">{busy || !subscriptionChecked ? (malay ? 'Menyemak…' : 'Checking…') : enabled ? (malay ? 'Matikan pada peranti ini' : 'Turn off on this device') : (malay ? 'Hidupkan notifikasi' : 'Turn on notifications')}</span></button> : null}{state !== 'unsupported' ? <><button type="button" onClick={checkWorker} className="min-h-11 rounded-xl px-2 text-xs font-semibold text-forest-800 underline underline-offset-2">{malay ? 'Semak perkhidmatan' : 'Check service'}</button><button type="button" onClick={checkBackgroundPush} className="min-h-11 rounded-xl px-2 text-xs font-semibold text-forest-800 underline underline-offset-2">{malay ? 'Semak push latar belakang' : 'Check background push'}</button></> : null}</div>{message ? <p className="mt-2 break-words text-xs leading-5 text-gray-600" role="status">{message}</p> : null}{workerMessage ? <p className="mt-2 break-words text-xs leading-5 text-gray-600" role="status">{workerMessage}</p> : null}{backgroundMessage ? <p className="mt-2 break-words text-xs leading-5 text-gray-600" role="status">{backgroundMessage}</p> : null}</div>;
}
