/*
# Delivery Batches (Foundation)

## Summary
Adds the Delivery Batch concept to FreshGo. A batch represents ONE Lalamove
trip that carries MANY packed customer orders from the supplier (Pasar Tani
Putrajaya) to the FreshGo Hub (Residensi Rimbun), where a FreshGo Rider then
delivers each order to the customer.

This migration ONLY creates the database structure. Order assignment,
the Rider dashboard, and customer tracking are intentionally NOT part of
this phase.

## New table: delivery_batches
- `id`                  uuid PK (gen_random_uuid)
- `batch_code`          text UNIQUE (e.g. BATCH-20260803-001, generated by the app)
- `delivery_date`       date — the delivery day the batch serves
- `supplier_name`       text — supplier packing at Pasar Tani Putrajaya
- `supplier_notes`      text — packing / pickup notes for the supplier
- `hub_name`            text default 'Residensi Rimbun' — FreshGo Hub destination
- `lalamove_tracking_url` text — optional Lalamove trip tracking link
- `status`              text default 'pending' (CHECK constrained):
                         pending | packing | awaiting_lalamove | in_transit_to_hub
                         | arrived_at_hub | completed | cancelled
- `created_by`          uuid FK auth.users
- `created_at` / `updated_at` timestamptz

## Orders change
- Adds ONE nullable column `delivery_batch_id uuid REFERENCES delivery_batches(id)
  ON DELETE SET NULL`. No other Orders columns are touched.

## RLS
- Authenticated users may read all batches.
- Only admins may insert / update / delete.

Idempotent: all CREATE/ALTER/POLICY are guarded.
*/

-- 1. delivery_batches table
CREATE TABLE IF NOT EXISTS public.delivery_batches (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_code           text NOT NULL UNIQUE,
  delivery_date        date NOT NULL,
  supplier_name        text,
  supplier_notes       text,
  hub_name             text NOT NULL DEFAULT 'Residensi Rimbun',
  lalamove_tracking_url text,
  status               text NOT NULL DEFAULT 'pending',
  created_by           uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- Status whitelist
ALTER TABLE public.delivery_batches
  DROP CONSTRAINT IF EXISTS delivery_batches_status_check;
ALTER TABLE public.delivery_batches
  ADD CONSTRAINT delivery_batches_status_check
  CHECK (status IN ('pending','packing','awaiting_lalamove','in_transit_to_hub','arrived_at_hub','completed','cancelled'));

-- 2. RLS
ALTER TABLE public.delivery_batches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_delivery_batches" ON public.delivery_batches;
CREATE POLICY "read_delivery_batches" ON public.delivery_batches
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "admin_insert_delivery_batches" ON public.delivery_batches;
CREATE POLICY "admin_insert_delivery_batches" ON public.delivery_batches
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "admin_update_delivery_batches" ON public.delivery_batches;
CREATE POLICY "admin_update_delivery_batches" ON public.delivery_batches
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "admin_delete_delivery_batches" ON public.delivery_batches;
CREATE POLICY "admin_delete_delivery_batches" ON public.delivery_batches
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- 3. Orders snapshot column (ONE nullable column, nothing else touched)
ALTER TABLE "Orders"
  ADD COLUMN IF NOT EXISTS delivery_batch_id uuid REFERENCES public.delivery_batches(id) ON DELETE SET NULL;

-- 4. Indexes for list sorting (delivery_date DESC) and assignment lookups
CREATE INDEX IF NOT EXISTS idx_delivery_batches_date ON public.delivery_batches (delivery_date DESC);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_batch_id ON "Orders" (delivery_batch_id);
